[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
itertools = "0.13.0"
nalgebra-glm = "0.18.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.10.0"
